# Generated by Django 2.0.3 on 2018-03-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('hash', models.CharField(max_length=264, unique=True)),
                ('n_tx', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('received_time', models.DateTimeField(blank=True, null=True)),
                ('prev_block', models.CharField(max_length=264)),
                ('next_block', models.CharField(blank=True, max_length=264, null=True)),
                ('prev_block_url', models.CharField(max_length=1000)),
                ('next_block_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
